// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlurHashCanvas: typeof import('./src/components/BlurHashCanvas.vue')['default']
    CandlestickChart: typeof import('./src/components/modules/candlestickChart.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FullText: typeof import('./src/components/FullText.vue')['default']
    HeatMapChart: typeof import('./src/components/HeatMapChart.vue')['default']
    LinkList: typeof import('./src/components/LinkList.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LocalRouter: typeof import('./src/components/LocalRouter.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    PieChart: typeof import('./src/components/modules/pieChart.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    QuoteCard: typeof import('./src/components/QuoteCard.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchTips: typeof import('./src/components/SearchTips.vue')['default']
    SinglePageHeader: typeof import('./src/components/SinglePageHeader.vue')['default']
    Tmv2ChartWithoutDataSet: typeof import('./src/components/Tmv2ChartWithoutDataSet.vue')['default']
    Tmv2Image: typeof import('./src/components/Tmv2Image.vue')['default']
    Tmv2Table: typeof import('./src/components/Tmv2Table.vue')['default']
    TO_FIX_Tmv2Chart: typeof import('./src/components/TO_FIX_Tmv2Chart.vue')['default']
    Translate: typeof import('./src/components/Translate.vue')['default']
    TwCard: typeof import('./src/components/TwCard.vue')['default']
    TweetImages: typeof import('./src/components/TweetImages.vue')['default']
    TweetItem: typeof import('./src/components/TweetItem.vue')['default']
    Tweets: typeof import('./src/components/Tweets.vue')['default']
    TwPolls: typeof import('./src/components/TwPolls.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}

export { }
