// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarRaceCharts: typeof import('./src/components/Charts/BarRaceCharts.vue')['default']
    BarStackChart: typeof import('./src/components/Charts/BarStackChart.vue')['default']
    BlurHashCanvas: typeof import('./src/components/BlurHashCanvas.vue')['default']
    CandlestickChart: typeof import('./src/components/modules/candlestickChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FullText: typeof import('./src/components/FullText.vue')['default']
    HashTagList: typeof import('./src/components/HashTagList.vue')['default']
    HeatMapChart: typeof import('./src/components/Charts/HeatMapChart.vue')['default']
    LineRaceChart: typeof import('./src/components/Charts/LineRaceChart.vue')['default']
    LinkList: typeof import('./src/components/LinkList.vue')['default']
    LocalRouter: typeof import('./src/components/LocalRouter.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    OnlineTrends: typeof import('./src/components/OnlineTrends.vue')['default']
    OnlineTweetItem: typeof import('./src/components/OnlineTweetItem.vue')['default']
    PieChart: typeof import('./src/components/modules/pieChart.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    QuoteCard: typeof import('./src/components/QuoteCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SearchTips: typeof import('./src/components/SearchTips.vue')['default']
    SinglePageHeader: typeof import('./src/components/SinglePageHeader.vue')['default']
    SunBurstChart: typeof import('./src/components/Charts/SunBurstChart.vue')['default']
    Tmv2ChartWithoutDataSet: typeof import('./src/components/Charts/Tmv2ChartWithoutDataSet.vue')['default']
    Tmv2Image: typeof import('./src/components/Tmv2Image.vue')['default']
    Tmv2Table: typeof import('./src/components/Tmv2Table.vue')['default']
    TO_FIX_Tmv2Chart: typeof import('./src/components/Charts/TO_FIX_Tmv2Chart.vue')['default']
    Translate: typeof import('./src/components/Translate.vue')['default']
    TwBroadcast: typeof import('./src/components/TwBroadcast.vue')['default']
    TwCard: typeof import('./src/components/TwCard.vue')['default']
    TwCollection: typeof import('./src/components/TwCollection.vue')['default']
    TweetAlbumItem: typeof import('./src/components/TweetAlbumItem.vue')['default']
    TweetImages: typeof import('./src/components/TweetImages.vue')['default']
    TweetItem: typeof import('./src/components/TweetItem.vue')['default']
    Tweets: typeof import('./src/components/Tweets.vue')['default']
    TwPolls: typeof import('./src/components/TwPolls.vue')['default']
    TwSpace: typeof import('./src/components/TwSpace.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    WordCloudChart: typeof import('./src/components/Charts/WordCloudChart.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
